version: '3.9'

services:
  postgres:
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "${PGDATA}"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - rds-data:/var/lib/postgresql/data  
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d backendrds"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    labels:
      NAME: "postgres_bk"

  backend_rds:
    image: 954976286648.dkr.ecr.us-east-1.amazonaws.com/backend-rds:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
    ports:
      - "8081:8081"

  redis:
    image: redis:7.4.2-alpine
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"

  backend_redis:
    image: 954976286648.dkr.ecr.us-east-1.amazonaws.com/backend-redis:latest
    depends_on:
      - redis
    environment:
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports:
      - "8080:8080"

  frontend:
    image: frontend:0.1.0
    ports:
      - "3000:80"  # Assuming the frontend serves on port 80 inside the container

volumes:
  rds-data:

