name: Deploy Backend RDS
on:
   push:
     branches:
       - develop
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
                # role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}                              
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug AWS Credentials
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
        # - name: Login to AWS
        #run: |
        #  echo "Logging into AWS ECR"
        #  aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_BACKEND_RDS }}

      - name: Build and Push Docker Image backend_rds
        run: |
          docker build -t backend_rds . -f ./backend_rds/Dockerfile
          docker tag backend_rds:latest ${{secrets.ECR_REPOSITORY_BACKEND_RDS}}:latest
          docker push ${{secrets.ECR_REPOSITORY_BACKEND_RDS}}:latest

